name: roleta_analyzer_pro_demo
description: App Flutter para análise de roleta com estratégias matemáticas.
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
